// <auto-generated />
using System;
using App.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Postgres.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Models.ContactHistory", b =>
                {
                    b.Property<int>("ContactHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContactHistoryId"));

                    b.Property<DateTime>("ContactDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContactDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("OutcomeStatusCode")
                        .HasColumnType("integer");

                    b.HasKey("ContactHistoryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OutcomeStatusCode");

                    b.ToTable("ContactHistory");
                });

            modelBuilder.Entity("App.Models.CustomerAsset", b =>
                {
                    b.Property<int>("CustomerAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerAssetId"));

                    b.Property<int>("AssetTypeCode")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAssetAcquired")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CustomerAssetId");

                    b.HasIndex("AssetTypeCode");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAsset");
                });

            modelBuilder.Entity("App.Models.CustomerLoyalty", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateFirstPurchase")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateLastPurchase")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtherLoyaltyDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.ToTable("CustomerLoyalty");
                });

            modelBuilder.Entity("App.Models.CustomerOffer", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialOfferId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfferAccepted")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CustomerId", "SpecialOfferId");

                    b.HasIndex("SpecialOfferId");

                    b.ToTable("CustomerOffer");
                });

            modelBuilder.Entity("App.Models.CustomerPreference", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("FactorCode")
                        .HasColumnType("integer");

                    b.HasKey("CustomerId", "FactorCode");

                    b.HasIndex("FactorCode");

                    b.ToTable("CustomerPreference");
                });

            modelBuilder.Entity("App.Models.CustomerProductHolding", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAcquired")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDiscontinued")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CustomerId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CustomerProductHolding");
                });

            modelBuilder.Entity("App.Models.CustomerProfile", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CustomerDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.ToTable("CustomerProfile");
                });

            modelBuilder.Entity("App.Models.HouseholdMember", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("CountOfChildren")
                        .HasColumnType("integer");

                    b.Property<int>("CountOfWageEarners")
                        .HasColumnType("integer");

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer");

                    b.HasKey("CustomerId");

                    b.ToTable("HouseholdMember");
                });

            modelBuilder.Entity("App.Models.RefAssetType", b =>
                {
                    b.Property<int>("AssetTypeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssetTypeCode"));

                    b.Property<string>("AssetTypeDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AssetTypeCode");

                    b.ToTable("RefAssetType");
                });

            modelBuilder.Entity("App.Models.RefContactOutcome", b =>
                {
                    b.Property<int>("OutcomeStatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OutcomeStatusCode"));

                    b.Property<string>("OutcomeStatusDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OutcomeStatusCode");

                    b.ToTable("RefContactOutcome");
                });

            modelBuilder.Entity("App.Models.RefPreferenceFactor", b =>
                {
                    b.Property<int>("FactorCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FactorCode"));

                    b.Property<string>("FactorDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FactorCode");

                    b.ToTable("RefPreferenceFactor");
                });

            modelBuilder.Entity("App.Models.ServiceAndProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.ToTable("ServiceAndProduct");
                });

            modelBuilder.Entity("App.Models.SpecialOffer", b =>
                {
                    b.Property<int>("SpecialOfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpecialOfferId"));

                    b.Property<string>("SpecialOfferDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpecialOfferId");

                    b.ToTable("SpecialOffer");
                });

            modelBuilder.Entity("App.Models.ContactHistory", b =>
                {
                    b.HasOne("App.Models.CustomerProfile", "Customer")
                        .WithMany("ContactHistories")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Models.RefContactOutcome", "RefContactOutcome")
                        .WithMany("ContactHistories")
                        .HasForeignKey("OutcomeStatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("RefContactOutcome");
                });

            modelBuilder.Entity("App.Models.CustomerAsset", b =>
                {
                    b.HasOne("App.Models.RefAssetType", "RefAssetType")
                        .WithMany("CustomerAssets")
                        .HasForeignKey("AssetTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Models.CustomerProfile", "Customer")
                        .WithMany("CustomerAssets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("RefAssetType");
                });

            modelBuilder.Entity("App.Models.CustomerLoyalty", b =>
                {
                    b.HasOne("App.Models.CustomerProfile", "Customer")
                        .WithMany("CustomerLoyalties")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("App.Models.CustomerOffer", b =>
                {
                    b.HasOne("App.Models.CustomerProfile", "Customer")
                        .WithMany("CustomerOffers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Models.SpecialOffer", "SpecialOffer")
                        .WithMany("CustomerOffers")
                        .HasForeignKey("SpecialOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("SpecialOffer");
                });

            modelBuilder.Entity("App.Models.CustomerPreference", b =>
                {
                    b.HasOne("App.Models.CustomerProfile", "Customer")
                        .WithMany("CustomerPreferences")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Models.RefPreferenceFactor", "RefPreferenceFactor")
                        .WithMany("CustomerPreferences")
                        .HasForeignKey("FactorCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("RefPreferenceFactor");
                });

            modelBuilder.Entity("App.Models.CustomerProductHolding", b =>
                {
                    b.HasOne("App.Models.CustomerProfile", "Customer")
                        .WithMany("CustomerProductHoldings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Models.ServiceAndProduct", "ServiceAndProduct")
                        .WithMany("CustomerProductHoldings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ServiceAndProduct");
                });

            modelBuilder.Entity("App.Models.HouseholdMember", b =>
                {
                    b.HasOne("App.Models.CustomerProfile", "Customer")
                        .WithMany("HouseholdMembers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("App.Models.CustomerProfile", b =>
                {
                    b.Navigation("ContactHistories");

                    b.Navigation("CustomerAssets");

                    b.Navigation("CustomerLoyalties");

                    b.Navigation("CustomerOffers");

                    b.Navigation("CustomerPreferences");

                    b.Navigation("CustomerProductHoldings");

                    b.Navigation("HouseholdMembers");
                });

            modelBuilder.Entity("App.Models.RefAssetType", b =>
                {
                    b.Navigation("CustomerAssets");
                });

            modelBuilder.Entity("App.Models.RefContactOutcome", b =>
                {
                    b.Navigation("ContactHistories");
                });

            modelBuilder.Entity("App.Models.RefPreferenceFactor", b =>
                {
                    b.Navigation("CustomerPreferences");
                });

            modelBuilder.Entity("App.Models.ServiceAndProduct", b =>
                {
                    b.Navigation("CustomerProductHoldings");
                });

            modelBuilder.Entity("App.Models.SpecialOffer", b =>
                {
                    b.Navigation("CustomerOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
